name: Build and Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: 17
      
      - name: Install dependencies
        run: npm ci --no-optional
    
      - name: Publish to Open VSX
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          tag: ${{ github.ref }}
          overwrite: true

